--liquibase formatted sql

-- changeset hospitalao:003-01-criar-tabela-token-blacklist splitStatements:false
CREATE TABLE token_blacklist (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(500) NOT NULL, expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT token_blacklist_pkey PRIMARY KEY (id), CONSTRAINT uq_token_blacklist_token UNIQUE (token));
CREATE INDEX idx_token_blacklist_token ON token_blacklist(token);
CREATE INDEX idx_token_blacklist_expiry ON token_blacklist(expiry_date);

--rollback DROP TABLE token_blacklist;
