--liquibase formatted sql

-- changeset hospitalao:001-00-criar-schema-auditoria splitStatements:false
CREATE SCHEMA IF NOT EXISTS auditoria;

--rollback DROP SCHEMA IF EXISTS auditoria CASCADE;

-- changeset hospitalao:001-01-tipos-enum splitStatements:false
DO $$ BEGIN
                CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE');
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
DO $$ BEGIN
                CREATE TYPE register_status_enum AS ENUM (
                    'ACTIVE',
                    'INACTIVE',
                    'SUSPENDED'
                );
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
DO $$ BEGIN
                CREATE TYPE episode_type_enum AS ENUM (
                    'EMERGENCY',
                    'OUTPATIENT',
                    'INPATIENT',
                    'OUTPATIENT_SURGERY',
                    'EXAM'
                );
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;

--rollback DROP TYPE IF EXISTS episode_type_enum;
--rollback DROP TYPE IF EXISTS register_status_enum;
--rollback DROP TYPE IF EXISTS gender_enum;

-- changeset hospitalao:001-02-tabela-auditoria splitStatements:false
CREATE TABLE auditoria.audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id UUID, user_name VARCHAR(200), table_name VARCHAR(100) NOT NULL, record_id VARCHAR(100) NOT NULL, operation VARCHAR(10) NOT NULL, previous_data JSONB, new_data JSONB, origin_ip VARCHAR(45), created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT audit_log_pkey PRIMARY KEY (id));
CREATE INDEX idx_audit_table_record ON auditoria.audit_log(table_name, record_id);
CREATE INDEX idx_audit_created_at ON auditoria.audit_log(created_at);

--rollback DROP TABLE auditoria.audit_log;
